### ISSUE TITLE
Erro de sintaxe no nome do pacote

### ISSUE THREAD

**Issue by andreipaz** [matAlmeida/cpf-generator#1]
Ñ está sendo possível importar o pacote na minha aplicacao por causa do hífen no nome: 

```shell
 from cpf-generator import CPF
            ^
SyntaxError: invalid syntax
```

Estou usando python 3.7

**Comment by ghost** [comment]
Olá Andei, tudo bem?

Eu e um colega também tivemos o mesmo erro. Acredito que seja pelo fato de que o python não aceita o caractere "-". A solução que encontrei foi a seguinte:

Peguei o código abaixo na internet e salvei como _cpf_generator.py_

```
import random

def generate_cpf():
    cpf = [random.randint(0, 9) for x in range(9)]

    for _ in range(2):
        val = sum([(len(cpf) + 1 - i) * v for i, v in enumerate(cpf)]) % 11

        cpf.append(11 - val if val > 1 else 0)

    return '%s%s%s.%s%s%s.%s%s%s-%s%s' % tuple(cpf)

```
Depois fiz a importação e realizei a chamada do método.

```
from cpf_generator import generate_cpf()

print(generate_cpf())
```

Espero ter auxiliado!

**Comment by matAlmeida** [comment]
Corrigido em v2.0.3

Desculpa pela demora
